# Generated by Django 5.0.2 on 2024-02-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ'),
        ),
    ]
